"""Measured and explicitly inferred constants for the Sage site reconstruction."""

FT = 0.3048
SITE_GRADE = -2.75

# A1.0 longitudinal chain, measured from the street property line in model +Y.
PARCEL_WIDTH = 50.0
PARCEL_LENGTH = 196.25
UPPER_FRONT_SETBACK = 28 + 9.5 / 12
UPPER_FRONT_OVERHANG = 1 + 4.5 / 12
FIRST_FLOOR_SETBACK = UPPER_FRONT_SETBACK + UPPER_FRONT_OVERHANG
MAIN_HOUSE_LENGTH = 49.5
HOUSE_TO_UNIT = 32.0
DETACHED_ALONG = 12.0
UNIT_TO_GARAGE = 47.0
GARAGE_ALONG = 22.0
ALLEY_SETBACK = 3 + 7 / 12

PROPERTY_FRONT_Y = -FIRST_FLOOR_SETBACK
PROPERTY_REAR_Y = PROPERTY_FRONT_Y + PARCEL_LENGTH
PROPERTY_WEST_X = -5.0
PROPERTY_EAST_X = PROPERTY_WEST_X + PARCEL_WIDTH

DETACHED_FRONT_Y = MAIN_HOUSE_LENGTH + HOUSE_TO_UNIT
DETACHED_REAR_Y = DETACHED_FRONT_Y + DETACHED_ALONG
DETACHED_WIDTH = 17 + 11 / 12
DETACHED_WEST_X = 0.0
DETACHED_EAST_X = DETACHED_WEST_X + DETACHED_WIDTH

GARAGE_FRONT_Y = DETACHED_REAR_Y + UNIT_TO_GARAGE
GARAGE_REAR_Y = GARAGE_FRONT_Y + GARAGE_ALONG
GARAGE_WIDTH = 13.0
GARAGE_WEST_X = -3.0
GARAGE_EAST_X = GARAGE_WEST_X + GARAGE_WIDTH


def longitudinal_chain():
    return (
        UPPER_FRONT_SETBACK + UPPER_FRONT_OVERHANG + MAIN_HOUSE_LENGTH
        + HOUSE_TO_UNIT + DETACHED_ALONG + UNIT_TO_GARAGE
        + GARAGE_ALONG + ALLEY_SETBACK
    )
